---
applicationName: "Ethan DS-API Hash Enhancer"
version: "0.1"

#Client Environment Settings
inFileLocation: "./sampleData/syntheticData.csv"
outFileLocation: "./sampleData/syntheticDataDone.csv"
fileHeaderRows: 1
chunkProcessingSize: 1000

#Security Settings
acxiomKey: ""
acxiomSecret: ""
grantType: "client_credentials"
tokenEndpoint: "https://login.myacxiom.com/api/v1/auth/oauth2/token"


#DS-API Settings
dsapiUri: "https://test.api.acxiom.com/v1"
dsapiPeopleEndpoint: "https://test.api.acxiom.com/people/"
lookupType: "sha1"
limit: 1
tenant: ""
role: ""
format: "json"
dsapiRequestBundles:
 - basicDemographics

#Bundle Reference, can be added to the request bundles dict above
dsapiPersonDataBundles:
 - causesAndVolunteer
 - dining
 - gambling
 - interests
 - political
 - socialMedia
 - acxiomOptOut
 - marketingSuppression
 - postalCompliance
 - emailContact
 - phoneContact
 - postalContact
 - areaDemographicsGS
 - basicDemographics
 - birthYearMonth
 - dob
 - eTechDemographics
 - personicxDigital
 - personicxFinancial
 - personicxHispanic
 - personicxInsurance
 - personicxLifestage
 - bankingAndServices
 - creditAndBankCards
 - discretionaryIncomeSemcasting
 - incomeRangePremiumSemcasting
 - insurance
 - investmentsAndAssets
 - mortgagesAndLoans
 - abilitec
 - householdId
 - mediaConsumption
 - inputEmailAddress
 - inputName
 - inputPhoneNumber
 - inputPostalAddress
 - matchMetadata
 - validationErrors
 - alcohol
 - gamingAndVideos
 - healthAndMedical
 - healthWellness
 - mobilePhonesAndCarriers
 - personalServices
 - technology
 - tobacco
 - travelAndEntertainment
 - vacationPropertySemcasting
 - purchaseFactors
 - shoppingAndPurchaseChannel
 - productPurchases
 - spending
 - vehicleAffinity
 - vehicleFinance
 - vehicleIMT
 - vehicleOwnership
dsapiHouseholdBundles:
 - basicDemographics
 - financialAssets
 - abilitec
 - inputEmailAddress
 - inputName
 - inputPhoneNumber
 - inputPostalAddress
 - matchMetadata
 - validationErrors
dsapiEntityBundles:
 - abilitec
 - abilitecHousehold
 - householdId
 - personIds
 - placeId
 - inputEmailAddress
 - inputName
 - inputPhoneNumber
 - inputPostalAddress
 - matchMetadata
 - validationErrors
 - ownershipAndOccupancy
lookupTypeList: 
 - er
 - sha1
 - abilitec
formatList:
 - json
 - xml
 - html

#Entity Creation Elements
person:
 Name:
  - firstName
  - middleName
  - lastName
  - suffix
 Address:
  - primaryNumber
  - preDirectional
  - street
  - streetSuffix
  - postDirectional
  - unitDesignator
  - secondaryNumber
  - city
  - state
  - zipCode
 Phone:
  - phoneNumber
 Email:
  - emailAddress 
